# Generated by Django 4.2.2 on 2026-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField()),
                ('rss_MB', models.FloatField()),
                ('stack_latency_ms', models.FloatField()),
                ('final_score', models.FloatField()),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('recommended_action', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='incidents_i_created_8be57d_idx')],
            },
        ),
    ]
