# Generated by Django 4.2.2 on 2026-02-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='stress_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
    ]
